[fmt]
line_length = 120
tab_width = 2
bracket_spacing = false
int_types = 'long'
quote_style = 'single'
number_underscore = 'thousands'
multiline_func_header = 'params_first_multi'
sort_imports = true

[profile.default]
solc_version = '0.8.30'
evm_version = 'prague'
libs = ['node_modules']
optimizer_runs = 10_000
ast = true
build_info = true
extra_output = ["storageLayout"]

[profile.optimized]
via_ir = true
out = 'out-via-ir'
ast = true

[profile.test]
via_ir = true
ast = true
build_info = true
extra_output = ["storageLayout"]

[profile.docs]
src = 'src/interfaces/'

[fuzz]
runs = 1000

[invariant]
timeout = 30
depth = 128
show_metrics = true
fail_on_revert = true
corpus_dir = 'test/invariants/fuzz/corpus'
show_solidity = true

[rpc_endpoints]
base = "${BASE_RPC}"
geo = "${GEO_RPC}"

[etherscan]
base = { key = "${BASESCAN_API_KEY}" }
geo = { key = "${GEO_API_KEY}" }
