[fmt]
line_length = 120
tab_width = 2
bracket_spacing = false
int_types = 'long'
quote_style = 'single'
number_underscore = 'thousands'
multiline_func_header = 'params_first_multi'
sort_imports = true

[profile.default]
solc_version = '0.8.35'
evm_version = 'prague'
libs = ['node_modules']
optimizer_runs = 10_000
via_ir = true
ast = true
build_info = true
extra_output = ['storageLayout']

[profile.optimized]
via_ir = true
out = 'out-via-ir'
ast = true

[profile.test]
via_ir = true
ast = true
build_info = true
extra_output = ['storageLayout']

[profile.docs]
src = 'src/interfaces/'

[fuzz]
runs = 1000

[invariant]
timeout = 30
depth = 128
show_metrics = true
fail_on_revert = true
show_solidity = true

[profile.invariant_l2.invariant]
corpus_dir = 'test/invariants/L2/fuzz/corpus'

[profile.invariant_l3.invariant]
corpus_dir = 'test/invariants/L3/fuzz/corpus'

[rpc_endpoints]
ethereum_mainnet = "${ETHEREUM_MAINNET_RPC}"
ethereum_sepolia = "${ETHEREUM_SEPOLIA_RPC}"
arbitrum_one = "${ARBITRUM_ONE_RPC}"
arbitrum_sepolia = "${ARBITRUM_SEPOLIA_RPC}"
geo = "${GEO_RPC}"
geo_testnet = "${GEO_TESTNET_RPC}"

[etherscan]
1 = { key = "${ETHERSCAN_API_KEY}" }
11155111 = { key = "${ETHERSCAN_API_KEY}" }
42161 = { key = "${ARBISCAN_API_KEY}" }
421614 = { key = "${ARBISCAN_API_KEY}", url = "${ARBISCAN_API_URL}" }
"${GEO_CHAIN_ID}" = { key = "${GEOSCAN_API_KEY}", url = "${GEOSCAN_API_URL}" }
"${GEO_TESTNET_CHAIN_ID}" = { key = "${GEOSCAN_API_KEY}", url = "${GEOSCAN_TESTNET_API_URL}" }
